## CEMTEC - Manipulação dos dados da estação solarimétrica em tempo real, a fim de desenvolver um DashBoard

### 1. Entendendo como funciona os arquivos TXT antigos, nome das colunas, o que cada coluna representa.

Ano dos arquivos: 2025

Espectroradiômetro: É um equipamento utilizado para medir a radiação eletromagnética em função do comprimento de onda.

Piranômetro: São sensores radiométricos utilizados para medir a irradiância solar incidente em uma superfície, sendo aplicados principalmente na medição da irradiância global horizontal e da irradiância difusa.

Estação Compacta: É um sistema que monitora variáveis metereológicas e ambientais, como a temperatura, umidade, pressão, vento e radiação.

#### 1.1 Preparando o ambiente:

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time
import warnings
from pandas.errors import DtypeWarning

warnings.filterwarnings("ignore", category=DtypeWarning)

%matplotlib inline
plt.rcParams["figure.figsize"] = (8, 5)

#### 1.1 Dados da Estação Compacta 2019

In [3]:
df = pd.read_table("WS600_Estação_Compacta_2019.txt", header = 1, sep=",") #header = 1, começa a considerar a partir da segunda linha
df.head()

,TIMESTAMP,RECORD,Temp_Ar,Humid_Ar,Ponto_Orvalho_act,Press_Ar,Vento_avg,Dir_Vento_act,Intens_Chuva,Chuva_Diff,Chuva_Diff_Tot
0,TS,RN,C,%,C,hPa,m/s,Deg,mm/h,mm,mm
1,NaN,NaN,Smp,Smp,Smp,Smp,Smp,Smp,Smp,Smp,Tot
2,2019-01-01 00:00:00,1445900,21.6,88.3,19.6,923,0.7,162.4,0,0,0
3,2019-01-01 00:00:10,1445901,21.6,88.3,19.6,923,0.7,169.1,0,0,0
4,2019-01-01 00:00:20,1445902,21.6,88.3,19.6,923,0.7,170,0,0,0

In [9]:
print(df.drop([0, 1]))
df.head()

                  TIMESTAMP   RECORD Temp_Ar Humid_Ar Ponto_Orvalho_act  \
2       2019-01-01 00:00:00  1445900    21.6     88.3              19.6
3       2019-01-01 00:00:10  1445901    21.6     88.3              19.6
4       2019-01-01 00:00:20  1445902    21.6     88.3              19.6
5       2019-01-01 00:00:30  1445903    21.6     88.3              19.6
6       2019-01-01 00:00:40  1445904    21.6     88.3              19.6
...                     ...      ...     ...      ...               ...
172496  2019-01-20 23:59:10  1618394    25.1     73.9              20.1
172497  2019-01-20 23:59:20  1618395    25.1     73.9              20.1
172498  2019-01-20 23:59:30  1618396    25.1     73.9              20.1
172499  2019-01-20 23:59:40  1618397    25.1     74.0              20.1
172500  2019-01-20 23:59:50  1618398    25.1     74.0              20.1

       Press_Ar Vento_avg Dir_Vento_act Intens_Chuva Chuva_Diff Chuva_Diff_Tot
2           923       0.7         162.4            0          0              0
3           923       0.7         169.1            0          0              0
4           923       0.7           170            0          0              0
5           923       0.7         152.8            0          0              0
6           923       0.7         168.9            0          0              0
...         ...       ...           ...          ...        ...            ...
172496      924       0.9          77.0          0.0        0.0            0.0
172497      924       0.9          91.4          0.0        0.0            0.0
172498      924       0.9          89.6          0.0        0.0            0.0
172499      924       0.9          91.1          0.0        0.0            0.0
172500      924       0.9          95.0          0.0        0.0            0.0

[172499 rows x 11 columns]

,TIMESTAMP,RECORD,Temp_Ar,Humid_Ar,Ponto_Orvalho_act,Press_Ar,Vento_avg,Dir_Vento_act,Intens_Chuva,Chuva_Diff,Chuva_Diff_Tot
0,TS,RN,C,%,C,hPa,m/s,Deg,mm/h,mm,mm
1,NaN,NaN,Smp,Smp,Smp,Smp,Smp,Smp,Smp,Smp,Tot
2,2019-01-01 00:00:00,1445900,21.6,88.3,19.6,923,0.7,162.4,0,0,0
3,2019-01-01 00:00:10,1445901,21.6,88.3,19.6,923,0.7,169.1,0,0,0
4,2019-01-01 00:00:20,1445902,21.6,88.3,19.6,923,0.7,170,0,0,0

Anatomia da Tabela

In [31]:
print("(Número de Linhas, Número de Colunas) :",df.shape, "\n")
print("Nome das Colunas :",df.columns, "\n")
print("Tipo de dado de cada coluna :",df.dtypes, "\n")
print("Quantidade de linhas: ",len(df))

(Número de Linhas, Número de Colunas) : (172501, 11)

Nome das Colunas : Index(['TIMESTAMP', 'RECORD', 'Temp_Ar', 'Humid_Ar', 'Ponto_Orvalho_act',
       'Press_Ar', 'Vento_avg', 'Dir_Vento_act', 'Intens_Chuva', 'Chuva_Diff',
       'Chuva_Diff_Tot'],
      dtype='str')

Tipo de dado de cada coluna : TIMESTAMP               str
RECORD               object
Temp_Ar              object
Humid_Ar             object
Ponto_Orvalho_act    object
Press_Ar             object
Vento_avg            object
Dir_Vento_act        object
Intens_Chuva         object
Chuva_Diff           object
Chuva_Diff_Tot       object
dtype: object

Quantidade de linhas:  172501

Selecionando os dados mais antigos

In [7]:
dados_mais_antigos = df.loc[2:6, ["TIMESTAMP", "RECORD", "Temp_Ar", "Humid_Ar", "Ponto_Orvalho_act", "Press_Ar", "Vento_avg", "Dir_Vento_act", "Intens_Chuva", "Chuva_Diff", "Chuva_Diff_Tot"]]
dados_mais_antigos

,TIMESTAMP,RECORD,Temp_Ar,Humid_Ar,Ponto_Orvalho_act,Press_Ar,Vento_avg,Dir_Vento_act,Intens_Chuva,Chuva_Diff,Chuva_Diff_Tot
2,2019-01-01 00:00:00,1445900,21.6,88.3,19.6,923,0.7,162.4,0,0,0
3,2019-01-01 00:00:10,1445901,21.6,88.3,19.6,923,0.7,169.1,0,0,0
4,2019-01-01 00:00:20,1445902,21.6,88.3,19.6,923,0.7,170,0,0,0
5,2019-01-01 00:00:30,1445903,21.6,88.3,19.6,923,0.7,152.8,0,0,0
6,2019-01-01 00:00:40,1445904,21.6,88.3,19.6,923,0.7,168.9,0,0,0

Selecionando os dados mais recentes

In [92]:
dados_mais_recentes = df.iloc[-1:, 0:13]
dados_mais_recentes

,TIMESTAMP,RECORD,Temp_Ar,Humid_Ar,Ponto_Orvalho_act,Press_Ar,Vento_avg,Dir_Vento_act,Intens_Chuva,Chuva_Diff,Chuva_Diff_Tot
172501,2022-12-25 19:19:19,1618399,25.1,74.0,20.1,924,0.9,95.0,0.0,1.0,0.0

Selecionando o Registro mais recente (maior RECORD)

In [83]:
numero_linha = len(df) - 1
record = df["RECORD"][numero_linha]
record

1618398

Programa que monitora se um dado novo foi adicionado

In [ ]:
#Entrada de variáveis
ultima_linha_analisada = 0
ultimo_registro_analisado = 0
quantidade_linhas = len(df)

#Verificando se houve alteração
while True:
    df = pd.read_table("WS600_Estação_Compacta_2019.txt", header = 1, sep=",")
    numero_linha = len(df) - 1
    ultimo_registro = df["RECORD"][numero_linha]
    if ultimo_registro>ultimo_registro_analisado:
        dados_mais_recentes = df.iloc[-1:, 0:13]
        ultimo_registro_analisado = ultimo_registro
        print(dados_mais_recentes)
        print("------------------"*10)
    time.sleep(10)

Testando com os dados simulados

In [102]:
df2 = pd.read_table("dados_simulados.txt", header = 1, sep=",")

In [ ]:
#Entrada de variáveis
ultima_linha_analisada = 0
ultimo_registro_analisado = 0

#Verificando se houve alteração
while True:
    df2 = pd.read_table("dados_simulados.txt", header = 1, sep=",")
    numero_linha = len(df2) - 1
    ultimo_registro = int(df2["RECORD"][numero_linha])
    if ultimo_registro>ultimo_registro_analisado:
        dados_mais_recentes = df2.iloc[-1:, 0:13]
        ultimo_registro_analisado = ultimo_registro
        print(dados_mais_recentes)
        print("------------------"*10)
    time.sleep(10)